### ISSUE TITLE
Publish to GitHub Pages?

### ISSUE THREAD

**Issue by stuartpb** [Miserlou/Horngry#1]
https://stupidhackathon.github.io/2015.html links to https://pubmail.io/static/horngry/index.html which is a dead link - would you be able to [flip the switch in this repo's settings](https://github.com/Miserlou/Horngry/settings) to enable publishing `master` as a site via GitHub Pages, so this could be accessed via https://miserlou.github.io/Horngry/index.html?

**Comment by Miserlou** [comment]
Wow, great idea. Done.
